<?php
/** 
 * code generated by vog
 * https://github.com/MarvinWank/vog
 */
declare(strict_types=1);

namespace Test\TestObjects;


use UnexpectedValueException;
use BadMethodCallException;

final class SetWithPrimitiveType implements Set,\Countable,\ArrayAccess,\Iterator
{        
    private array $items;
    private int $position;
        
    private function __construct(array $items = [])
    {
        $this->position = 0;
        $this->items = $items;
    }    public static function fromArray(array $items) {
        foreach ($items as $key => $item) {
            $type = gettype($item);
            if($type !== 'string'){
                throw new UnexpectedValueException('array expects items of string but has ' . $type . ' on index ' . $key);
            }  
        }
        return new self($items);
    }
    
    public function toArray() {
        return $this->items;
    }
    public function equals(?self $other): bool
    {
        $ref = $this->toArray();
        $val = $other->toArray();
                
        return ($ref === $val);
    }
    
    public function add(string $item): self {
        $values = $this->toArray();
        $values[] = $item;
        return self::fromArray($values);
    }
    
    
    public function contains(string $item): bool {
        return array_search($item, $this->items) !== false;
    }
    
    public function count(): int
    {
        return count($this->items);
    }
    
        public function offsetExists($offset) {
        return isset($this->items[$offset]);
    }

    public function offsetSet($offset, $value) {
        throw new BadMethodCallException('ArrayAccess offsetSet is forbidden, use ->add()');
    }

    public function offsetGet($offset) {
        return $this->items[$offset];
    }

    public function offsetUnset($offset) {
        throw new BadMethodCallException('ArrayAccess offsetUnset is forbidden, use ->remove()');
    }

    public function current() {
        return $this->items[$this->position];
    }

    public function rewind() {
        $this->position = 0;
    }

    public function key() {
        return $this->position;
    }

    public function next() {
        ++$this->position;
    }

    public function valid() {
        return isset($this->items[$this->position]);
    }
    
    public function remove(string $item): self {
        $values = $this->toArray();
        if(($key = array_search($item, $values)) !== false) {
            unset($values[$key]);
        }
        $values = array_values($values);
        
        return self::fromArray($values);
    }
}