<?php
/** 
 * code generated by vog
 * https://github.com/MarvinWank/vog
 */
declare(strict_types=1);

namespace Vog\ValueObjects;


use InvalidArgumentException;

class VogTypes implements Enum
{
    public const VALUES = ['set', 'enum', 'nullableEnum', 'valueObject', ];               
    public const NAMES = ['set', 'enum', 'nullableEnum', 'valueObject', ];               
    public const OPTIONS = [ 
        'set' => 'set',
        'enum' => 'enum',
        'nullableEnum' => 'nullableEnum',
        'valueObject' => 'valueObject',
    ];

    public const set = 'set';               
    public const enum = 'enum';               
    public const nullableEnum = 'nullableEnum';               
    public const valueObject = 'valueObject';                       
    private string $name;
    private string $value;
        
    private function __construct(string $name)
    {
        $this->name = $name;
        $this->value = self::OPTIONS[$name];
    }

    public static function set(): self
    {
        return new self('set');
    }
    
    public static function enum(): self
    {
        return new self('enum');
    }
    
    public static function nullableEnum(): self
    {
        return new self('nullableEnum');
    }
    
    public static function valueObject(): self
    {
        return new self('valueObject');
    }
    
    public static function fromValue(string $value): self
    {
        foreach (self::OPTIONS as $key => $option) {
            if ($value === $option) {
                return new self($key);
            }
        }

        throw new InvalidArgumentException("Unknown enum value '$value' given");
    }
    
    public static function fromName(string $name): self
    {
        if(!array_key_exists($name, self::OPTIONS)){
             throw new InvalidArgumentException("Unknown enum name $name given");
        }
        
        return new self($name);
    }
    
    public function equals(?self $other): bool
    {
        return (null !== $other) && ($this->name() === $other->name());
    }

    public function name(): string
    {
        return $this->name;
    }

    public function value(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function toString(): string
    {
        return $this->name;
    }
}